language: python

python:
  - "2.7"

# command to install dependencies
install: 
  -  pip install -r requirements.txt --use-mirrors
  -  pip install coveralls --use-mirrors

# command to run tests
script: 
  -  python manage.py test djikiki
  -  coverage run --source="." manage.py test djikiki

after_success:
  - coveralls  